sudo: required
language: node_js
node_js:
  - 8
rvm:
  - 2.0.0

before_install:
- gem install sass
- rvm install ruby-2.0.0-p598
- gem install scss_lint
- npm cache clear --force
- npm install gulp
- npm install
script:
- gulp prod
