init:
  - git config --global core.autocrlf false
environment:
  matrix:
  - ruby_verison: 22-x64

install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version
  - gem install sass
  - gem install scss_lint
  - npm install -g npm
  - npm install gulp -g
  - npm install
test_script:
  - gulp prod
build: off
matrix:
  fast_finish: true
cache:
  - node_modules -> package.json
