init:
  - git config --global core.autocrlf false
environment:
  matrix:
  - nodejs_version: "8"
install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version
  - gem install sass
  - gem install scss_lint -v 0.56.0
  - npm install -g npm
  - npm install gulp -g
  - npm install
test_script:
  - gulp prod
build: off
matrix:
  fast_finish: true

